package graphql.java.client.domain.forum;

import java.util.List;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * @author generated by graphql-maven-plugin
 * @See https://github.com/graphql-java-generator/graphql-java-generator
 */
public class QueryTypeTopics {

	@JsonDeserialize(contentAs = Topic.class)
	List<Topic> topics;

	public void setTopics(List<Topic> topics) {
		this.topics = topics;
	}

	public List<Topic> getTopics() {
		return topics;
	}
	
    public String toString() {
        return "QueryTypeTopics {topics: " + topics + "}";
    }
}
