// Generated by delombok at Mon Dec 22 16:05:30 CET 2025
package com.graphql_java_generator.plugin.generate_code;

import com.graphql_java_generator.plugin.conf.CustomScalarDefinition;
import com.graphql_java_generator.util.GraphqlUtils;
import graphql.schema.GraphQLScalarType;

/**
 * This class contains the data that allows to generate a custom Jackson serializer. These serializers are used to
 * serialize the parameters in the outgoing requests. The serializers exist only for what's not JSON standard, that is:
 * GraphQL Custom Scalars. In the generated code, there is one serializer for each list depth level for this type, that
 * has been encountered in the GraphQL schema.<BR/>
 * For instance <code>Date</code> is not a list, and thus has a depth level of 0, whereas <code>[[Date]]</code> is a
 * list of lists, and thus has a depth level of 2.
 * 
 * @author etienne-sf
 */
public class CustomSerializer {
	/**
	 * The name of the GraphQL type is used to name the java class for the serialization
	 */
	private String graphQLTypeName;
	/**
	 * The Java type (for instance java.lang.String), that represent the GraphQL type.<BR/>
	 * For instance, for a GraphQLType <I>[[String]]</I>, the <I>javaClassFullName</I> would contain
	 * <I>List<List<java.lang.String>></I>
	 */
	private String itemJavaClassFullName;
	/**
	 * The {@link CustomScalarDefinition} that contains the information to declare the {@link GraphQLScalarType}.
	 */
	private CustomScalarDefinition customScalarDefinition;
	/**
	 * Indicates at which level of nested array this custom deserializer is. To deserialize a value (for custom scalar),
	 * the <I>listLevel</I> is 0. To deserialize a <I>[[Character]]</I>, the <I>listLevel</I> is 2.
	 */
	private int listDepth;

	/**
	 * Returns the simple name for the serializer class.
	 * 
	 * @return The simple name looks like this: <I>ListListDate</I>, where:
	 *         <UL>
	 *         <LI>ListList shows that this custom scalar is a list serializer. It reads items that are at level 2 of
	 *         nested GraphQL arrays (= Java list).</LI>
	 *         <LI>Date is the GraphQL type name that is managed by this serializer</LI>
	 *         </UL>
	 */
	public String getClassSimpleName() {
		return getCustomSerializerClassSimpleName(listDepth, GraphqlUtils.graphqlUtils.getJavaName(graphQLTypeName));
	}

	/**
	 * Returns The Java type (for instance java.lang.String), that represent the GraphQL type.<BR/>
	 * For instance, for a GraphQLType <I>[[String]]</I>, the <I>javaClassFullName</I> would contain
	 * <I>List<List<java.lang.String>></I>
	 * 
	 * @return
	 */
	public String getJavaClassFullName() {
		String ret = itemJavaClassFullName;
		for (int i = 1; i <= listDepth; i += 1) {
			ret = "List<" + ret + ">";
		}
		return ret;
	}

	/**
	 * Standard utility to calculate a Custom Serializer name. Used in this class, and to define the Jackson annotation
	 * on the field
	 * 
	 * @param listLevel
	 *            Indicates at which level of nested array this custom serializer is. To serialize a value (for custom
	 *            scalar), the <I>listLevel</I> is 0. To serialize a <I>[[Character]]</I>, the <I>listLevel</I> is 2.
	 * @param itemClassSimpleName
	 *            The class simple name of the item of the list. For instance, for a field that is
	 *            <I>List&lt;List&lt;Date&gt;&gt;</I>, the <I>itemClassSimpleName</I> would be <I>Date</I>
	 * @return
	 */
	public static String getCustomSerializerClassSimpleName(int listLevel, String graphQLTypeName) {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < listLevel; i += 1) {
			sb.append("List");
		}
		sb.append(graphQLTypeName);
		return sb.toString();
	}

	/**
	 * The name of the GraphQL type is used to name the java class for the serialization
	 */
	
	
	public String getGraphQLTypeName() {
		return this.graphQLTypeName;
	}

	/**
	 * The Java type (for instance java.lang.String), that represent the GraphQL type.<BR/>
	 * For instance, for a GraphQLType <I>[[String]]</I>, the <I>javaClassFullName</I> would contain
	 * <I>List<List<java.lang.String>></I>
	 */
	
	
	public String getItemJavaClassFullName() {
		return this.itemJavaClassFullName;
	}

	/**
	 * The {@link CustomScalarDefinition} that contains the information to declare the {@link GraphQLScalarType}.
	 */
	
	
	public CustomScalarDefinition getCustomScalarDefinition() {
		return this.customScalarDefinition;
	}

	/**
	 * Indicates at which level of nested array this custom deserializer is. To deserialize a value (for custom scalar),
	 * the <I>listLevel</I> is 0. To deserialize a <I>[[Character]]</I>, the <I>listLevel</I> is 2.
	 */
	
	
	public int getListDepth() {
		return this.listDepth;
	}

	/**
	 * The name of the GraphQL type is used to name the java class for the serialization
	 */
	
	
	public void setGraphQLTypeName(final String graphQLTypeName) {
		this.graphQLTypeName = graphQLTypeName;
	}

	/**
	 * The Java type (for instance java.lang.String), that represent the GraphQL type.<BR/>
	 * For instance, for a GraphQLType <I>[[String]]</I>, the <I>javaClassFullName</I> would contain
	 * <I>List<List<java.lang.String>></I>
	 */
	
	
	public void setItemJavaClassFullName(final String itemJavaClassFullName) {
		this.itemJavaClassFullName = itemJavaClassFullName;
	}

	/**
	 * The {@link CustomScalarDefinition} that contains the information to declare the {@link GraphQLScalarType}.
	 */
	
	
	public void setCustomScalarDefinition(final CustomScalarDefinition customScalarDefinition) {
		this.customScalarDefinition = customScalarDefinition;
	}

	/**
	 * Indicates at which level of nested array this custom deserializer is. To deserialize a value (for custom scalar),
	 * the <I>listLevel</I> is 0. To deserialize a <I>[[Character]]</I>, the <I>listLevel</I> is 2.
	 */
	
	
	public void setListDepth(final int listDepth) {
		this.listDepth = listDepth;
	}

	@java.lang.Override
	
	
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof CustomSerializer)) return false;
		final CustomSerializer other = (CustomSerializer) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.getListDepth() != other.getListDepth()) return false;
		final java.lang.Object this$graphQLTypeName = this.getGraphQLTypeName();
		final java.lang.Object other$graphQLTypeName = other.getGraphQLTypeName();
		if (this$graphQLTypeName == null ? other$graphQLTypeName != null : !this$graphQLTypeName.equals(other$graphQLTypeName)) return false;
		final java.lang.Object this$itemJavaClassFullName = this.getItemJavaClassFullName();
		final java.lang.Object other$itemJavaClassFullName = other.getItemJavaClassFullName();
		if (this$itemJavaClassFullName == null ? other$itemJavaClassFullName != null : !this$itemJavaClassFullName.equals(other$itemJavaClassFullName)) return false;
		final java.lang.Object this$customScalarDefinition = this.getCustomScalarDefinition();
		final java.lang.Object other$customScalarDefinition = other.getCustomScalarDefinition();
		if (this$customScalarDefinition == null ? other$customScalarDefinition != null : !this$customScalarDefinition.equals(other$customScalarDefinition)) return false;
		return true;
	}

	
	
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof CustomSerializer;
	}

	@java.lang.Override
	
	
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getListDepth();
		final java.lang.Object $graphQLTypeName = this.getGraphQLTypeName();
		result = result * PRIME + ($graphQLTypeName == null ? 43 : $graphQLTypeName.hashCode());
		final java.lang.Object $itemJavaClassFullName = this.getItemJavaClassFullName();
		result = result * PRIME + ($itemJavaClassFullName == null ? 43 : $itemJavaClassFullName.hashCode());
		final java.lang.Object $customScalarDefinition = this.getCustomScalarDefinition();
		result = result * PRIME + ($customScalarDefinition == null ? 43 : $customScalarDefinition.hashCode());
		return result;
	}

	@java.lang.Override
	
	
	public java.lang.String toString() {
		return "CustomSerializer(graphQLTypeName=" + this.getGraphQLTypeName() + ", itemJavaClassFullName=" + this.getItemJavaClassFullName() + ", customScalarDefinition=" + this.getCustomScalarDefinition() + ", listDepth=" + this.getListDepth() + ")";
	}

	/**
	 * Creates a new {@code CustomSerializer} instance.
	 *
	 * @param graphQLTypeName The name of the GraphQL type is used to name the java class for the serialization
	 * @param itemJavaClassFullName The Java type (for instance java.lang.String), that represent the GraphQL type.<BR/>
	 * For instance, for a GraphQLType <I>[[String]]</I>, the <I>javaClassFullName</I> would contain
	 * <I>List<List<java.lang.String>></I>
	 * @param customScalarDefinition The {@link CustomScalarDefinition} that contains the information to declare the {@link GraphQLScalarType}.
	 * @param listDepth Indicates at which level of nested array this custom deserializer is. To deserialize a value (for custom scalar),
	 * the <I>listLevel</I> is 0. To deserialize a <I>[[Character]]</I>, the <I>listLevel</I> is 2.
	 */
	
	
	public CustomSerializer(final String graphQLTypeName, final String itemJavaClassFullName, final CustomScalarDefinition customScalarDefinition, final int listDepth) {
		this.graphQLTypeName = graphQLTypeName;
		this.itemJavaClassFullName = itemJavaClassFullName;
		this.customScalarDefinition = customScalarDefinition;
		this.listDepth = listDepth;
	}
}
