package com.graphql_java_generator.client.domain.starwars;

import com.graphql_java_generator.annotation.GraphQLEnumType;

/**
 * @author generated by graphql-java-generator
 * @see <a href=
 *      "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLEnumType("Episode")
public enum Episode {
	NEWHOPE, EMPIRE, JEDI;
}
