package com.graphql_java_generator.client.domain.starwars;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import com.graphql_java_generator.client.response.GraphQLRequestObject;

/**
 * @author generated by graphql-java-generator
 * @see <a href=
 *      "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
public class MutationTypeCreateHuman implements GraphQLRequestObject {

	public static final String NAME = "createHuman";

	@JsonProperty("createHuman")
	Human createHuman;

	public void setCreateHuman(Human createHuman) {
		this.createHuman = createHuman;
	}

	public Human getCreateHuman() {
		return createHuman;
	}

	@Override
	public String toString() {
		return "MutationTypeCreateHuman {createHuman: " + createHuman + "}";
	}

	@Override
	public void setExtensions(JsonNode extensions) {
		// TODO Auto-generated method stub

	}
}
