package com.graphql_java_generator.plugin.compilation_tests;

import graphql.mavenplugin_notscannedbyspring.AllGraphQLCases_Server_SpringConfiguration_util_batchMapping_MonoMap;

class AllGraphQLCasesServer_util_batchMapping_MonoMap_Test extends AllGraphQLCasesServer_util_batchMapping_Test {

	public AllGraphQLCasesServer_util_batchMapping_MonoMap_Test() {
		super(AllGraphQLCases_Server_SpringConfiguration_util_batchMapping_MonoMap.class);
	}
}
