/** Generated by the default template from graphql-java-generator */
package com.graphql_java_generator.server.domain.forum;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href=
 *      "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("TopicInput")
public class TopicInput {

	public TopicInput() {
		// No action
	}

	@GraphQLScalar(fieldName = "boardId", graphQLTypeSimpleName = "ID",  javaClass = String.class)
	String boardId;

	@GraphQLNonScalar(fieldName = "input", graphQLTypeSimpleName = "TopicPostInput",  javaClass = TopicPostInput.class)
	TopicPostInput input;

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	public String getBoardId() {
		return boardId;
	}

	public void setInput(TopicPostInput input) {
		this.input = input;
	}

	public TopicPostInput getInput() {
		return input;
	}

	@Override
	public String toString() {
		return "TopicInput {" + "boardId: " + boardId + ", " + "input: " + input + "}";
	}

	/**
	 * Enum of field names
	 */
	public static enum Field implements GraphQLField {
		BoardId("boardId"), Input("input");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		@Override
		public String getFieldName() {
			return fieldName;
		}

		@Override
		public Class<?> getGraphQLType() {
			return this.getClass().getDeclaringClass();
		}

	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * Builder
	 */
	public static class Builder {
		private String boardId;
		private TopicPostInput input;

		public Builder withBoardId(String boardId) {
			this.boardId = boardId;
			return this;
		}

		public Builder withInput(TopicPostInput input) {
			this.input = input;
			return this;
		}

		public TopicInput build() {
			TopicInput _object = new TopicInput();
			_object.setBoardId(boardId);
			_object.setInput(input);
			return _object;
		}
	}
}
