// Generated by delombok at Mon Dec 22 16:05:30 CET 2025
/**
 *
 */
package com.graphql_java_generator.plugin.language.impl;

import java.util.ArrayList;
import java.util.List;
import com.graphql_java_generator.plugin.DocumentParser;
import com.graphql_java_generator.plugin.conf.CommonConfiguration;
import com.graphql_java_generator.plugin.conf.GenerateCodeCommonConfiguration;
import com.graphql_java_generator.plugin.language.EnumValue;
import com.graphql_java_generator.plugin.language.Field;

/**
 * This class is the image for a graphql Enum
 * 
 * @author etienne-sf
 */
public class EnumType extends AbstractType {
	/**
	 * The list of values
	 */
	List<EnumValue> values = new ArrayList<>();

	/**
	 * @param name
	 *            The name of this enum type
	 * @param configuration
	 *            The current plugin configuration, which is accessible through an interface that extends
	 *            {@link CommonConfiguration}
	 * @param documentParser
	 *            The {@link DocumentParser} that has parsed the schema, and so that contains the whole schema
	 *            definition
	 */
	public EnumType(String name, CommonConfiguration configuration, DocumentParser documentParser) {
		super(name, GraphQlType.ENUM, configuration, documentParser);
	}

	/**
	 * An enum has no identifier.
	 * 
	 * @return null
	 */
	@Override
	public List<Field> getIdentifiers() {
		return new ArrayList<>();
	}

	@Override
	public String getPackageName() {
		return ((GenerateCodeCommonConfiguration) configuration).getPackageName();
	}

	@Override
	public boolean isInputType() {
		return false;
	}

	@Override
	public boolean isCustomScalar() {
		return false;
	}

	@Override
	public boolean isEnum() {
		return true;
	}

	@Override
	public boolean isScalar() {
		return true;
	}

	@Override
	protected String getPrefix() {
		return configuration.getEnumPrefix();
	}

	@Override
	protected String getSuffix() {
		return configuration.getEnumSuffix();
	}

	/**
	 * The list of values
	 */
	
	
	public List<EnumValue> getValues() {
		return this.values;
	}

	/**
	 * The list of values
	 */
	
	
	public void setValues(final List<EnumValue> values) {
		this.values = values;
	}

	@java.lang.Override
	
	
	public java.lang.String toString() {
		return "EnumType(values=" + this.getValues() + ")";
	}

	@java.lang.Override
	
	
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof EnumType)) return false;
		final EnumType other = (EnumType) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$values = this.getValues();
		final java.lang.Object other$values = other.getValues();
		if (this$values == null ? other$values != null : !this$values.equals(other$values)) return false;
		return true;
	}

	
	
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof EnumType;
	}

	@java.lang.Override
	
	
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		final java.lang.Object $values = this.getValues();
		result = result * PRIME + ($values == null ? 43 : $values.hashCode());
		return result;
	}
}
