package com.graphql_java_generator.client.domain.forum;

import java.util.List;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * @author generated by graphql-java-generator
 * @See https://github.com/graphql-java-generator/graphql-java-generator
 */
public class MutationTypeCreateTopic {

	Topic createTopic;

	public void setCreateTopic(Topic createTopic) {
		this.createTopic = createTopic;
	}

	public Topic getCreateTopic() {
		return createTopic;
	}
	
    public String toString() {
        return "MutationTypeCreateTopic {createTopic: " + createTopic + "}";
    }
}
