package com.graphql_java_generator.client.domain.forum;

import java.util.List;
import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */

public class PostInput  {

	@GraphQLScalar(graphqlType = UUID.class)
	UUID topicId;


	@GraphQLNonScalar(graphqlType = TopicPostInput.class)
	TopicPostInput input;



	public void setTopicId(UUID topicId) {
		this.topicId = topicId;
	}

	public UUID getTopicId() {
		return topicId;
	}

	public void setInput(TopicPostInput input) {
		this.input = input;
	}

	public TopicPostInput getInput() {
		return input;
	}

    public String toString() {
        return "PostInput {"
				+ "topicId: " + topicId
				+ ", "
				+ "input: " + input
        		+ "}";
    }
}
