package com.graphql_java_generator.client.domain.forum;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLCustomScalar;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @See https://github.com/graphql-java-generator/graphql-java-generator
 */

public class Post {

	@GraphQLScalar(graphQLTypeName = "ID", javaClass = String.class)
	String id;

	@JsonDeserialize(using = CustomScalarDeserializerDate.class)
	@GraphQLCustomScalar(graphQLTypeName = "Date", javaClass = Date.class)
	Date date;

	@GraphQLNonScalar(graphQLTypeName = "Member", javaClass = Member.class)
	Member author;

	@GraphQLScalar(graphQLTypeName = "Boolean", javaClass = Boolean.class)
	Boolean publiclyAvailable;

	@GraphQLScalar(graphQLTypeName = "String", javaClass = String.class)
	String title;

	@GraphQLScalar(graphQLTypeName = "String", javaClass = String.class)
	String content;

	public void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getDate() {
		return date;
	}

	public void setAuthor(Member author) {
		this.author = author;
	}

	public Member getAuthor() {
		return author;
	}

	public void setPubliclyAvailable(Boolean publiclyAvailable) {
		this.publiclyAvailable = publiclyAvailable;
	}

	public Boolean getPubliclyAvailable() {
		return publiclyAvailable;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle() {
		return title;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getContent() {
		return content;
	}

	@Override
	public String toString() {
		return "Post {" + "id: " + id + ", " + "date: " + date + ", " + "author: " + author + ", "
				+ "publiclyAvailable: " + publiclyAvailable + ", " + "title: " + title + ", " + "content: " + content
				+ "}";
	}
}
