package com.graphql_java_generator.client.domain.forum;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;

import java.util.Date;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType
public class TopicPostInput  {

	@JsonProperty("authorId")
	@GraphQLScalar(graphQLTypeName = "ID", javaClass = String.class)
	String authorId;


	@JsonProperty("date")
	@JsonDeserialize(using = CustomScalarDeserializerDate.class)
	@GraphQLScalar(graphQLTypeName = "Date", javaClass = Date.class)
	Date date;


	@JsonProperty("publiclyAvailable")
	@GraphQLScalar(graphQLTypeName = "Boolean", javaClass = Boolean.class)
	Boolean publiclyAvailable;


	@JsonProperty("title")
	@GraphQLScalar(graphQLTypeName = "String", javaClass = String.class)
	String title;


	@JsonProperty("content")
	@GraphQLScalar(graphQLTypeName = "String", javaClass = String.class)
	String content;



	public void setAuthorId(String authorId) {
		this.authorId = authorId;
	}

	public String getAuthorId() {
		return authorId;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getDate() {
		return date;
	}

	public void setPubliclyAvailable(Boolean publiclyAvailable) {
		this.publiclyAvailable = publiclyAvailable;
	}

	public Boolean getPubliclyAvailable() {
		return publiclyAvailable;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle() {
		return title;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getContent() {
		return content;
	}

    public String toString() {
        return "TopicPostInput {"
				+ "authorId: " + authorId
				+ ", "
				+ "date: " + date
				+ ", "
				+ "publiclyAvailable: " + publiclyAvailable
				+ ", "
				+ "title: " + title
				+ ", "
				+ "content: " + content
        		+ "}";
    }

    /**
	 * Enum of field names
	 */
	 public static enum Field {
		AuthorId("authorId"),
		Date("date"),
		PubliclyAvailable("publiclyAvailable"),
		Title("title"),
		Content("content");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		public String getFieldName() {
			return fieldName;
		}

	}
}
