package com.graphql_java_generator.client.domain.forum;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href=
 *      "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("TopicInput")
public class TopicInput {

	@JsonProperty("boardId")
	@GraphQLScalar(graphQLTypeName = "ID", javaClass = String.class)
	String boardId;

	@JsonProperty("input")
	@GraphQLNonScalar(graphQLTypeName = "TopicPostInput", javaClass = TopicPostInput.class)
	TopicPostInput input;

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	public String getBoardId() {
		return boardId;
	}

	public void setInput(TopicPostInput input) {
		this.input = input;
	}

	public TopicPostInput getInput() {
		return input;
	}

	@Override
	public String toString() {
		return "TopicInput {" + "boardId: " + boardId + ", " + "input: " + input + "}";
	}

	/**
	 * Enum of field names
	 */
	public static enum Field {
		BoardId("boardId"), Input("input");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		public String getFieldName() {
			return fieldName;
		}

	}
}
