// Generated by delombok at Mon Dec 22 16:05:30 CET 2025
/**
 * 
 */
package com.graphql_java_generator.plugin.language;

/**
 * This class is a transcription of the GraphQL type of a field, as it has been read in the
 * <A HREF="https://en.wikipedia.org/wiki/Abstract_syntax_tree">AST</A>. When browsing through the GraphQL
 * <A HREF="https://en.wikipedia.org/wiki/Abstract_syntax_tree">AST</A>, the type may not already have been parsed. This
 * can occur when a field F1 of the type T1 refers to the T2 type, while the T2 type contains a F2 field, that is of the
 * T1 type.<BR/>
 * So, when reading the <A HREF="https://en.wikipedia.org/wiki/Abstract_syntax_tree">AST</A>, we only store the type
 * name, if it's mandatory and its structure (if it's a list, a list of list...). When generating the code, the whole
 * <A HREF="https://en.wikipedia.org/wiki/Abstract_syntax_tree">AST</A> has been read. At this moment, it's possible to
 * access to the instance of the {@link Type} for this type, and read all its properties (java class...)
 * 
 * @author etienne-sf
 */
public class FieldTypeAST {
	/**
	 * The type of this field, as defined in the GraphQL schema. This type is either the type of the field (if it's not
	 * a list), or the type of the items in the list (if it's a list)
	 */
	private String graphQLTypeSimpleName;
	// Allows the default value to be used with the Lombok @Builder annotation on the class
	/**
	 * The depth of the list for this input parameter: 0 if this field is not a list. And 2, for instance, if the
	 * field's type is "[[Int]]"
	 */
	int listDepth;
	// Allows the default value to be used with the Lombok @Builder annotation on the class
	/**
	 * Is this field mandatory? If this field is a list, then mandatory indicates whether the list itself is mandatory,
	 * or may be nullable. For item of the list, you'll have to call {@link #getListItemFieldTypeAST()}, to get the item
	 * list's properties.<BR/>
	 * By default, it's not a list
	 */
	boolean mandatory;
	// Allows the default value to be used with the Lombok @Builder annotation on the class
	/**
	 * Only used if this type is a list: it indicates if the items for this list are mandatory?
	 */
	boolean itemMandatory;
	// Allows the default value to be used with the Lombok @Builder annotation on the class
	/**
	 * When this field type is a list, returns the properties for the item of this list. This can also be a list, when
	 * the GraphQL type is defined by nested arrays.
	 * 
	 * @throws RuntimeException
	 *             When the current field type is not a list
	 */
	FieldTypeAST listItemFieldTypeAST;

	/**
	 * The default constructor
	 */
	public FieldTypeAST() {
	}

	/**
	 * The standard constructor
	 */
	public FieldTypeAST(String graphQLTypeName) {
		this.graphQLTypeSimpleName = graphQLTypeName;
	}

	/**
	 * Returns the java type as it an be used to declare a variable or an attribute. For instance, a field of GraphQL
	 * type <I>[ID]</I>, in client mode (where an ID is a java String), the result would be: <I>List&lt;String&gt;</I>.
	 * This always uses the java short name. So the proper import must be added into the enclosing java file.<BR/>
	 * The aim of this recursive method is to manage list of list of list of list...
	 */
	public String getJavaType(String classSimpleName) {
		if (this.listDepth > 0) return //
		//
		//
		//
		new StringBuilder().append(this.listDepth > 0 ? "List<" : "").append(this.listItemFieldTypeAST.getJavaType(classSimpleName)).append(this.listDepth > 0 ? ">" : "").toString();
		 else return classSimpleName;
	}

	/**
	 * The full type of this field, as defined in the GraphQL schema. For instance, a list of list of String, where
	 * everything is mandatory would be <I>[[String!]!]!</I>
	 */
	public String getGraphQLType() {
		if (this.listDepth > 0) return //
		//
		//
		//
		//
		new StringBuilder().append(this.listDepth > 0 ? "[" : "").append(this.listItemFieldTypeAST.getGraphQLType()).append(this.listDepth > 0 ? "]" : "").append(this.mandatory ? "!" : "").toString();
		 else return this.graphQLTypeSimpleName + (this.mandatory ? "!" : "");
	}

	public String getGraphQLTypeSimpleName() {
		if (this.listDepth > 0) return this.listItemFieldTypeAST.getGraphQLTypeSimpleName();
		 else return this.graphQLTypeSimpleName;
	}

	public void setGraphQLTypeName(String graphQLTypeName) {
		if (this.listDepth > 0) this.listItemFieldTypeAST.setGraphQLTypeName(graphQLTypeName);
		 else this.graphQLTypeSimpleName = graphQLTypeName;
	}

	
	
	private static int $default$listDepth() {
		return 0;
	}

	
	
	private static boolean $default$mandatory() {
		return false;
	}

	
	
	private static boolean $default$itemMandatory() {
		return false;
	}

	
	
	private static FieldTypeAST $default$listItemFieldTypeAST() {
		return null;
	}


	
	
	public static class FieldTypeASTBuilder {
		
		
		private String graphQLTypeSimpleName;
		
		
		private boolean listDepth$set;
		
		
		private int listDepth$value;
		
		
		private boolean mandatory$set;
		
		
		private boolean mandatory$value;
		
		
		private boolean itemMandatory$set;
		
		
		private boolean itemMandatory$value;
		
		
		private boolean listItemFieldTypeAST$set;
		
		
		private FieldTypeAST listItemFieldTypeAST$value;

		
		
		FieldTypeASTBuilder() {
		}

		/**
		 * The type of this field, as defined in the GraphQL schema. This type is either the type of the field (if it's not
		 * a list), or the type of the items in the list (if it's a list)
		 * @return {@code this}.
		 */
		
		
		public FieldTypeAST.FieldTypeASTBuilder graphQLTypeSimpleName(final String graphQLTypeSimpleName) {
			this.graphQLTypeSimpleName = graphQLTypeSimpleName;
			return this;
		}

		/**
		 * The depth of the list for this input parameter: 0 if this field is not a list. And 2, for instance, if the
		 * field's type is "[[Int]]"
		 * @return {@code this}.
		 */
		
		
		public FieldTypeAST.FieldTypeASTBuilder listDepth(final int listDepth) {
			this.listDepth$value = listDepth;
			listDepth$set = true;
			return this;
		}

		/**
		 * Is this field mandatory? If this field is a list, then mandatory indicates whether the list itself is mandatory,
		 * or may be nullable. For item of the list, you'll have to call {@link #getListItemFieldTypeAST()}, to get the item
		 * list's properties.<BR/>
		 * By default, it's not a list
		 * @return {@code this}.
		 */
		
		
		public FieldTypeAST.FieldTypeASTBuilder mandatory(final boolean mandatory) {
			this.mandatory$value = mandatory;
			mandatory$set = true;
			return this;
		}

		/**
		 * Only used if this type is a list: it indicates if the items for this list are mandatory?
		 * @return {@code this}.
		 */
		
		
		public FieldTypeAST.FieldTypeASTBuilder itemMandatory(final boolean itemMandatory) {
			this.itemMandatory$value = itemMandatory;
			itemMandatory$set = true;
			return this;
		}

		/**
		 * When this field type is a list, returns the properties for the item of this list. This can also be a list, when
		 * the GraphQL type is defined by nested arrays.
		 * 
		 * @throws RuntimeException
		 *             When the current field type is not a list
		 * @return {@code this}.
		 */
		
		
		public FieldTypeAST.FieldTypeASTBuilder listItemFieldTypeAST(final FieldTypeAST listItemFieldTypeAST) {
			this.listItemFieldTypeAST$value = listItemFieldTypeAST;
			listItemFieldTypeAST$set = true;
			return this;
		}

		
		
		public FieldTypeAST build() {
			int listDepth$value = this.listDepth$value;
			if (!this.listDepth$set) listDepth$value = FieldTypeAST.$default$listDepth();
			boolean mandatory$value = this.mandatory$value;
			if (!this.mandatory$set) mandatory$value = FieldTypeAST.$default$mandatory();
			boolean itemMandatory$value = this.itemMandatory$value;
			if (!this.itemMandatory$set) itemMandatory$value = FieldTypeAST.$default$itemMandatory();
			FieldTypeAST listItemFieldTypeAST$value = this.listItemFieldTypeAST$value;
			if (!this.listItemFieldTypeAST$set) listItemFieldTypeAST$value = FieldTypeAST.$default$listItemFieldTypeAST();
			return new FieldTypeAST(this.graphQLTypeSimpleName, listDepth$value, mandatory$value, itemMandatory$value, listItemFieldTypeAST$value);
		}

		@java.lang.Override
		
		
		public java.lang.String toString() {
			return "FieldTypeAST.FieldTypeASTBuilder(graphQLTypeSimpleName=" + this.graphQLTypeSimpleName + ", listDepth$value=" + this.listDepth$value + ", mandatory$value=" + this.mandatory$value + ", itemMandatory$value=" + this.itemMandatory$value + ", listItemFieldTypeAST$value=" + this.listItemFieldTypeAST$value + ")";
		}
	}

	
	
	public static FieldTypeAST.FieldTypeASTBuilder builder() {
		return new FieldTypeAST.FieldTypeASTBuilder();
	}

	
	
	public FieldTypeAST.FieldTypeASTBuilder toBuilder() {
		return new FieldTypeAST.FieldTypeASTBuilder().graphQLTypeSimpleName(this.graphQLTypeSimpleName).listDepth(this.listDepth).mandatory(this.mandatory).itemMandatory(this.itemMandatory).listItemFieldTypeAST(this.listItemFieldTypeAST);
	}

	/**
	 * The depth of the list for this input parameter: 0 if this field is not a list. And 2, for instance, if the
	 * field's type is "[[Int]]"
	 */
	
	
	public int getListDepth() {
		return this.listDepth;
	}

	/**
	 * Is this field mandatory? If this field is a list, then mandatory indicates whether the list itself is mandatory,
	 * or may be nullable. For item of the list, you'll have to call {@link #getListItemFieldTypeAST()}, to get the item
	 * list's properties.<BR/>
	 * By default, it's not a list
	 */
	
	
	public boolean isMandatory() {
		return this.mandatory;
	}

	/**
	 * Only used if this type is a list: it indicates if the items for this list are mandatory?
	 */
	
	
	public boolean isItemMandatory() {
		return this.itemMandatory;
	}

	/**
	 * When this field type is a list, returns the properties for the item of this list. This can also be a list, when
	 * the GraphQL type is defined by nested arrays.
	 * 
	 * @return
	 * @throws RuntimeException
	 *             When the current field type is not a list
	 */
	
	
	public FieldTypeAST getListItemFieldTypeAST() {
		return this.listItemFieldTypeAST;
	}

	/**
	 * The type of this field, as defined in the GraphQL schema. This type is either the type of the field (if it's not
	 * a list), or the type of the items in the list (if it's a list)
	 */
	
	
	public void setGraphQLTypeSimpleName(final String graphQLTypeSimpleName) {
		this.graphQLTypeSimpleName = graphQLTypeSimpleName;
	}

	/**
	 * The depth of the list for this input parameter: 0 if this field is not a list. And 2, for instance, if the
	 * field's type is "[[Int]]"
	 */
	
	
	public void setListDepth(final int listDepth) {
		this.listDepth = listDepth;
	}

	/**
	 * Is this field mandatory? If this field is a list, then mandatory indicates whether the list itself is mandatory,
	 * or may be nullable. For item of the list, you'll have to call {@link #getListItemFieldTypeAST()}, to get the item
	 * list's properties.<BR/>
	 * By default, it's not a list
	 */
	
	
	public void setMandatory(final boolean mandatory) {
		this.mandatory = mandatory;
	}

	/**
	 * Only used if this type is a list: it indicates if the items for this list are mandatory?
	 */
	
	
	public void setItemMandatory(final boolean itemMandatory) {
		this.itemMandatory = itemMandatory;
	}

	/**
	 * When this field type is a list, returns the properties for the item of this list. This can also be a list, when
	 * the GraphQL type is defined by nested arrays.
	 * 
	 * @throws RuntimeException
	 *             When the current field type is not a list
	 */
	
	
	public void setListItemFieldTypeAST(final FieldTypeAST listItemFieldTypeAST) {
		this.listItemFieldTypeAST = listItemFieldTypeAST;
	}

	@java.lang.Override
	
	
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof FieldTypeAST)) return false;
		final FieldTypeAST other = (FieldTypeAST) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.getListDepth() != other.getListDepth()) return false;
		if (this.isMandatory() != other.isMandatory()) return false;
		if (this.isItemMandatory() != other.isItemMandatory()) return false;
		final java.lang.Object this$graphQLTypeSimpleName = this.getGraphQLTypeSimpleName();
		final java.lang.Object other$graphQLTypeSimpleName = other.getGraphQLTypeSimpleName();
		if (this$graphQLTypeSimpleName == null ? other$graphQLTypeSimpleName != null : !this$graphQLTypeSimpleName.equals(other$graphQLTypeSimpleName)) return false;
		final java.lang.Object this$listItemFieldTypeAST = this.getListItemFieldTypeAST();
		final java.lang.Object other$listItemFieldTypeAST = other.getListItemFieldTypeAST();
		if (this$listItemFieldTypeAST == null ? other$listItemFieldTypeAST != null : !this$listItemFieldTypeAST.equals(other$listItemFieldTypeAST)) return false;
		return true;
	}

	
	
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof FieldTypeAST;
	}

	@java.lang.Override
	
	
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getListDepth();
		result = result * PRIME + (this.isMandatory() ? 79 : 97);
		result = result * PRIME + (this.isItemMandatory() ? 79 : 97);
		final java.lang.Object $graphQLTypeSimpleName = this.getGraphQLTypeSimpleName();
		result = result * PRIME + ($graphQLTypeSimpleName == null ? 43 : $graphQLTypeSimpleName.hashCode());
		final java.lang.Object $listItemFieldTypeAST = this.getListItemFieldTypeAST();
		result = result * PRIME + ($listItemFieldTypeAST == null ? 43 : $listItemFieldTypeAST.hashCode());
		return result;
	}

	@java.lang.Override
	
	
	public java.lang.String toString() {
		return "FieldTypeAST(graphQLTypeSimpleName=" + this.getGraphQLTypeSimpleName() + ", listDepth=" + this.getListDepth() + ", mandatory=" + this.isMandatory() + ", itemMandatory=" + this.isItemMandatory() + ", listItemFieldTypeAST=" + this.getListItemFieldTypeAST() + ")";
	}

	/**
	 * Creates a new {@code FieldTypeAST} instance.
	 *
	 * @param graphQLTypeSimpleName The type of this field, as defined in the GraphQL schema. This type is either the type of the field (if it's not
	 * a list), or the type of the items in the list (if it's a list)
	 * @param listDepth The depth of the list for this input parameter: 0 if this field is not a list. And 2, for instance, if the
	 * field's type is "[[Int]]"
	 * @param mandatory Is this field mandatory? If this field is a list, then mandatory indicates whether the list itself is mandatory,
	 * or may be nullable. For item of the list, you'll have to call {@link #getListItemFieldTypeAST()}, to get the item
	 * list's properties.<BR/>
	 * By default, it's not a list
	 * @param itemMandatory Only used if this type is a list: it indicates if the items for this list are mandatory?
	 * @param listItemFieldTypeAST When this field type is a list, returns the properties for the item of this list. This can also be a list, when
	 * the GraphQL type is defined by nested arrays.
	 * 
	 * @throws RuntimeException
	 *             When the current field type is not a list
	 */
	
	
	public FieldTypeAST(final String graphQLTypeSimpleName, final int listDepth, final boolean mandatory, final boolean itemMandatory, final FieldTypeAST listItemFieldTypeAST) {
		this.graphQLTypeSimpleName = graphQLTypeSimpleName;
		this.listDepth = listDepth;
		this.mandatory = mandatory;
		this.itemMandatory = itemMandatory;
		this.listItemFieldTypeAST = listItemFieldTypeAST;
	}
}
