##
## Velocity template for the BatchLoaderDelegateXxxxImpl classes, where Xxxx successively every object in the GraphQL schema
## which has an ID.
##
## This template has these inputs:
## package
## batchLoader
##
/** This template is custom **/
package ${pluginConfiguration.packageName};

import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import javax.annotation.Resource;

import org.dataloader.DataLoaderRegistry;
import org.springframework.stereotype.Component;

#foreach($import in $imports)
import $import;
#end

/**
 * This is the default implementation for BathLoaderDelegate. It is implemented for each object of the GraphQL model
 * that has a field of type ID, which is identified as an identifier. <BR/>
 * It can be used in a DataFetcherDelegate implementation in this way : 
 * <PRE>
 * &#64;Override
 * public CompletableFuture<List<${batchLoader.type.classSimpleName}>> friends(DataFetchingEnvironment environment, DataLoader<UUID, ${batchLoader.type.classSimpleName}> dataLoader,
 * 		${batchLoader.type.classSimpleName} source) {
 * 	logger.debug("Executing characterImpl.friends, with this character: {}", source.getId().toString());
 * 	List<UUID> friendIds = graphQLUtil
 * 			.convertListByteArrayToListUUID(characterRepository.findFriendsId(source.getId()));
 * 	return dataLoader.loadMany(friendIds);
 * }
 *
 * </PRE>
 * @author generated by graphql-java-generator
 */
@Component
public class BatchLoaderDelegate${batchLoader.type.classSimpleName}Impl implements BatchLoaderDelegate<UUID, ${batchLoader.type.classSimpleName}> {

	/** The DataFetcherDelegates contain the requests to the data */
	@Resource
	${batchLoader.dataFetchersDelegate.pascalCaseName} ${batchLoader.dataFetchersDelegate.camelCaseName};

	/**
	 * A batch loader function that will be called with N or more keys for batch loading. This can be a singleton object
	 * since it's stateless.
	 * 
	 * @param keys
	 *            the list of keys, for which we want to retrieve the instances.
	 * @return the list of ${batchLoader.type.classSimpleName}s corresponding to the given keys
	 */
	@Override
	public CompletionStage<List<${batchLoader.type.classSimpleName}>> load(List<${batchLoader.type.identifier.type.classSimpleName}> keys) {
		// We use supplyAsync() of values here for maximum parellisation
		return CompletableFuture.supplyAsync(() -> ${batchLoader.dataFetchersDelegate.camelCaseName}.batchLoader(keys));
	}

	/**
	 * The name for this {@link BatchLoaderDelegate}, as ot is stored in the {@link DataLoaderRegistry}. <BR/>
	 * The BatchLoader can then be retrieved by this command, in a DataFetchDelegate implementation:<BR/>
	 */
	@Override
	public String getName() {
		return "${batchLoader.type.classSimpleName}";
	}

}
