package ${pluginConfiguration.packageName};

import com.graphql_java_generator.annotation.GraphQLUnionType;


/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
${object.annotation}
public interface ${object.javaName} {

}
