package com.graphql_java_generator.client.domain.allGraphQLCases;

import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href=
 *      "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType
public class $class {

	@GraphQLScalar(graphQLTypeName = "String", javaClass = String.class)
	String $default;

	public void setDefault(String $default) {
		this.$default = $default;
	}

	public String getDefault() {
		return $default;
	}

	@Override
	public String toString() {
		return "$class {" + "$default: " + $default + "}";
	}
}
