package com.graphql_java_generator.client.domain.allGraphQLCases;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author generated by graphql-java-generator
 * @see <a href=
 *      "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
public class AnotherMutationTypeCreateAllFieldCases {

	@JsonProperty("createAllFieldCases")
	AllFieldCases createAllFieldCases;

	public void setCreateAllFieldCases(AllFieldCases createAllFieldCases) {
		this.createAllFieldCases = createAllFieldCases;
	}

	public AllFieldCases getCreateAllFieldCases() {
		return createAllFieldCases;
	}

	@Override
	public String toString() {
		return "AnotherMutationTypeCreateAllFieldCases {createAllFieldCases: " + createAllFieldCases + "}";
	}
}
