package com.graphql_java_generator.client.domain.allGraphQLCases;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLInterfaceType;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;
import com.graphql_java_generator.client.domain.starwars.Human;

/**
 * @author generated by graphql-java-generator
 * @see <a href=
 *      "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@JsonTypeInfo(use = Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "__typename")
@JsonSubTypes({ @Type(value = Droid.class, name = "Droid"), @Type(value = Human.class, name = "Human") })
@GraphQLInterfaceType("Character")
public interface Character {

	@GraphQLScalar(graphQLTypeName = "ID", javaClass = String.class)
	public void setId(String id);

	@GraphQLScalar(graphQLTypeName = "ID", javaClass = String.class)
	public String getId();

	@GraphQLScalar(graphQLTypeName = "String", javaClass = String.class)
	public void setName(String name);

	@GraphQLScalar(graphQLTypeName = "String", javaClass = String.class)
	public String getName();

	@GraphQLNonScalar(graphQLTypeName = "Character", javaClass = Character.class)
	public void setFriends(List<Character> friends);

	@GraphQLNonScalar(graphQLTypeName = "Character", javaClass = Character.class)
	public List<Character> getFriends();

	@JsonDeserialize(contentAs = Episode.class)
	@GraphQLScalar(graphQLTypeName = "Episode", javaClass = Episode.class)
	public void setAppearsIn(List<Episode> appearsIn);

	@JsonDeserialize(contentAs = Episode.class)
	@GraphQLScalar(graphQLTypeName = "Episode", javaClass = Episode.class)
	public List<Episode> getAppearsIn();
}
