/** Generated by the default template from graphql-java-generator */
package com.graphql_java_generator.client.domain.allGraphQLCases;

import com.graphql_java_generator.client.directive.Directive;
import com.graphql_java_generator.client.directive.DirectiveLocation;
import com.graphql_java_generator.client.directive.DirectiveRegistry;
import com.graphql_java_generator.client.directive.DirectiveRegistryImpl;
import com.graphql_java_generator.client.request.InputParameter;
import com.graphql_java_generator.client.request.InputParameter.InputParameterType;
import com.graphql_java_generator.customscalars.CustomScalarRegistryImpl;

public class DirectiveRegistryInitializer {
	
	/**
	 * Initialization of the {@link DirectiveRegistry} with all known custom scalars, that is with all custom scalars
	 * defined in the project pom
	 */
	public static DirectiveRegistry initDirectiveRegistry() {
		DirectiveRegistry directiveRegistry = new DirectiveRegistryImpl();
		Directive directive;
		InputParameter param;

		/////////////////////////////////////////////////////////////////////////////////////////////////////
		// Creating Directive skip
		/////////////////////////////////////////////////////////////////////////////////////////////////////
		directive = new Directive();
		directive.setName("skip");
		directive.setPackageName("com.graphql_java_generator.client.domain.allGraphQLCases");
		param = InputParameter.newHardCodedParameter("if", null,
					graphql.Scalars.GraphQLBoolean
					, true, false, false
				);
		directive.getArguments().add(param);
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD);
		directive.getDirectiveLocations().add(DirectiveLocation.FRAGMENT_SPREAD);
		directive.getDirectiveLocations().add(DirectiveLocation.INLINE_FRAGMENT);
		directiveRegistry.registerDirective(directive);

		/////////////////////////////////////////////////////////////////////////////////////////////////////
		// Creating Directive include
		/////////////////////////////////////////////////////////////////////////////////////////////////////
		directive = new Directive();
		directive.setName("include");
		directive.setPackageName("com.graphql_java_generator.client.domain.allGraphQLCases");
		param = InputParameter.newHardCodedParameter("if", null,
					graphql.Scalars.GraphQLBoolean
					, true, false, false
				);
		directive.getArguments().add(param);
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD);
		directive.getDirectiveLocations().add(DirectiveLocation.FRAGMENT_SPREAD);
		directive.getDirectiveLocations().add(DirectiveLocation.INLINE_FRAGMENT);
		directiveRegistry.registerDirective(directive);

		/////////////////////////////////////////////////////////////////////////////////////////////////////
		// Creating Directive defer
		/////////////////////////////////////////////////////////////////////////////////////////////////////
		directive = new Directive();
		directive.setName("defer");
		directive.setPackageName("com.graphql_java_generator.client.domain.allGraphQLCases");
		param = InputParameter.newHardCodedParameter("if", null,
					graphql.Scalars.GraphQLBoolean
					, true, false, false
				);
		directive.getArguments().add(param);
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD);
		directiveRegistry.registerDirective(directive);

		/////////////////////////////////////////////////////////////////////////////////////////////////////
		// Creating Directive deprecated
		/////////////////////////////////////////////////////////////////////////////////////////////////////
		directive = new Directive();
		directive.setName("deprecated");
		directive.setPackageName("com.graphql_java_generator.client.domain.allGraphQLCases");
		param = InputParameter.newHardCodedParameter("reason", null,
					graphql.Scalars.GraphQLString
					, false, false, false
				);
		directive.getArguments().add(param);
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD_DEFINITION);
		directive.getDirectiveLocations().add(DirectiveLocation.ENUM_VALUE);
		directiveRegistry.registerDirective(directive);

		/////////////////////////////////////////////////////////////////////////////////////////////////////
		// Creating Directive RelayConnection
		/////////////////////////////////////////////////////////////////////////////////////////////////////
		directive = new Directive();
		directive.setName("RelayConnection");
		directive.setPackageName("com.graphql_java_generator.client.domain.allGraphQLCases");
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD_DEFINITION);
		directiveRegistry.registerDirective(directive);

		/////////////////////////////////////////////////////////////////////////////////////////////////////
		// Creating Directive testDirective
		/////////////////////////////////////////////////////////////////////////////////////////////////////
		directive = new Directive();
		directive.setName("testDirective");
		directive.setPackageName("com.graphql_java_generator.client.domain.allGraphQLCases");
		param = InputParameter.newHardCodedParameter("value", null,
					graphql.Scalars.GraphQLString
					, true, false, false
				);
		directive.getArguments().add(param);
		param = InputParameter.newHardCodedParameter("anotherValue", null,
					graphql.Scalars.GraphQLString
					, false, false, false
				);
		directive.getArguments().add(param);
		param = InputParameter.newHardCodedParameter("anArray", null,
					graphql.Scalars.GraphQLString
					, false, true, true
				);
		directive.getArguments().add(param);
		param = InputParameter.newHardCodedParameter("anObject", null,
					CustomScalarRegistryImpl.customScalarRegistry.getGraphQLCustomScalarType("CharacterInput")
					, false, false, false
				);
		directive.getArguments().add(param);
		param = InputParameter.newHardCodedParameter("anInt", null,
					graphql.Scalars.GraphQLInt
					, false, false, false
				);
		directive.getArguments().add(param);
		param = InputParameter.newHardCodedParameter("aFloat", null,
					graphql.Scalars.GraphQLFloat
					, false, false, false
				);
		directive.getArguments().add(param);
		param = InputParameter.newHardCodedParameter("aBoolean", null,
					graphql.Scalars.GraphQLBoolean
					, false, false, false
				);
		directive.getArguments().add(param);
		param = InputParameter.newHardCodedParameter("anID", null,
					graphql.Scalars.GraphQLID
					, false, false, false
				);
		directive.getArguments().add(param);
		param = InputParameter.newHardCodedParameter("aCustomScalarDate", null,
					CustomScalarRegistryImpl.customScalarRegistry.getGraphQLCustomScalarType("Date")
					, false, false, false
				);
		directive.getArguments().add(param);
		directive.getDirectiveLocations().add(DirectiveLocation.QUERY);
		directive.getDirectiveLocations().add(DirectiveLocation.MUTATION);
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD);
		directive.getDirectiveLocations().add(DirectiveLocation.FRAGMENT_DEFINITION);
		directive.getDirectiveLocations().add(DirectiveLocation.FRAGMENT_SPREAD);
		directive.getDirectiveLocations().add(DirectiveLocation.INLINE_FRAGMENT);
		directive.getDirectiveLocations().add(DirectiveLocation.SCHEMA);
		directive.getDirectiveLocations().add(DirectiveLocation.SCALAR);
		directive.getDirectiveLocations().add(DirectiveLocation.OBJECT);
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD_DEFINITION);
		directive.getDirectiveLocations().add(DirectiveLocation.ARGUMENT_DEFINITION);
		directive.getDirectiveLocations().add(DirectiveLocation.INTERFACE);
		directive.getDirectiveLocations().add(DirectiveLocation.UNION);
		directive.getDirectiveLocations().add(DirectiveLocation.ENUM);
		directive.getDirectiveLocations().add(DirectiveLocation.ENUM_VALUE);
		directive.getDirectiveLocations().add(DirectiveLocation.INPUT_OBJECT);
		directive.getDirectiveLocations().add(DirectiveLocation.INPUT_FIELD_DEFINITION);
		directiveRegistry.registerDirective(directive);

		/////////////////////////////////////////////////////////////////////////////////////////////////////
		// Creating Directive anotherTestDirective
		/////////////////////////////////////////////////////////////////////////////////////////////////////
		directive = new Directive();
		directive.setName("anotherTestDirective");
		directive.setPackageName("com.graphql_java_generator.client.domain.allGraphQLCases");
		directive.getDirectiveLocations().add(DirectiveLocation.QUERY);
		directive.getDirectiveLocations().add(DirectiveLocation.MUTATION);
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD);
		directive.getDirectiveLocations().add(DirectiveLocation.FRAGMENT_DEFINITION);
		directive.getDirectiveLocations().add(DirectiveLocation.FRAGMENT_SPREAD);
		directive.getDirectiveLocations().add(DirectiveLocation.INLINE_FRAGMENT);
		directive.getDirectiveLocations().add(DirectiveLocation.SCHEMA);
		directive.getDirectiveLocations().add(DirectiveLocation.SCALAR);
		directive.getDirectiveLocations().add(DirectiveLocation.OBJECT);
		directive.getDirectiveLocations().add(DirectiveLocation.FIELD_DEFINITION);
		directive.getDirectiveLocations().add(DirectiveLocation.ARGUMENT_DEFINITION);
		directive.getDirectiveLocations().add(DirectiveLocation.INTERFACE);
		directive.getDirectiveLocations().add(DirectiveLocation.UNION);
		directive.getDirectiveLocations().add(DirectiveLocation.ENUM);
		directive.getDirectiveLocations().add(DirectiveLocation.ENUM_VALUE);
		directive.getDirectiveLocations().add(DirectiveLocation.INPUT_OBJECT);
		directive.getDirectiveLocations().add(DirectiveLocation.INPUT_FIELD_DEFINITION);
		directiveRegistry.registerDirective(directive);


		DirectiveRegistryImpl.directiveRegistry = directiveRegistry;
		return directiveRegistry;
	}

}
